name: examples
description: svg_to_path_generator_example
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  svg_to_path_annotation:
    git:
      url: https://github.com/karabanovbs/svg_to_path_generator
      path: packages/svg_to_path_annotation
      ref: 0.0.2+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^1.11.0
  svg_to_path_generator:
    git:
      url: https://github.com/karabanovbs/svg_to_path_generator
      path: packages/svg_to_path_generator
      ref: 0.0.2+4

flutter:
  uses-material-design: true